Updated all files with JsDocs
SwapnikKatkoori/Text-Summarizer pull request #15
Opened 2020-05-01 20:43 UTC by caelinsutch

For #8 

Still not done as of time of writing, just giving everyone a headsup that I'm working on this

2020-05-01 21:00 UTC, caelinsutch commented
@SwapnikKatkoori I left some comments where I'm not sure what the correct type is, or how the function works. If you could give me some guidance that'd be great! Once this is done I can make the Typescript typings

2020-05-02 01:10 UTC, zbot473 requested changes

2020-05-02 01:10 UTC, zbot473 commented on .gitignore
> +.idea/
If we're ignoring IDEs, maybe add `.vscode/` too

2020-05-02 01:14 UTC, caelinsutch commented on .gitignore
> +.idea/
I'll get that done. Can you look at those todos and write jsDocs for them?

2020-05-02 01:16 UTC, zbot473 commented on .gitignore
> +.idea/
Should I create a PR on your fork, or do you just want me to suggest changes?

2020-05-02 02:43 UTC, caelinsutch commented
You can clone my fork and make the change he’s there if you’d like.
-- 
Cheers,

Caelin
Owner - Caelin Sutch Creative - Photography, Videography, Graphic Design,
Web Design, and More!
caelinsutch@gmail.com
(916) 317 4484

2020-05-02 18:07 UTC, caelinsutch commented on .gitignore
> +.idea/
You can clone my fork and make the changes on the branch

2025-10-29 15:56 UTC, closed without merging